# Change these first
owner: shelwong
repo: benqservers 
user-agent: shelwong
sites:
  - name: BenQ AMS
    url: https://ams.benq.com/#/
  - name: BenQ IAM
    url: https://iam.benq.com/
  - name: BenQ DMS
    url: https://dms.benq.com/#/
    icon: https://dms.benq.com/client/dms_logo.svg    
  - name: BenQ X-Sign Broadcast
    url: https://x-signbroadcast.benq.com/
  - name: BenQ Service Portal
    url: https://service-portal.benq.com/login

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  
  baseUrl: /benqservers
  #logoUrl: https://dms.benq.com/client/dms_logo.svg
  logoUrl: /assets/BenQEducationLogo.jpg
  name: BenQ Servers North America
  introTitle: BenQ North America
  introMessage: See the status of the BenQ servers in North America
  
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: TestSite
      href: https://shelwong.github.io/MyWebsite/index.html
  

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
